# This source file is part of the Greatdori! open source project
#
# Copyright (c) 2025 the Greatdori! project authors
# Licensed under Apache License v2.0
#
# See https://greatdori.memz.top/LICENSE.txt for license information
# See https://greatdori.memz.top/CONTRIBUTORS.txt for the list of Greatdori! project authors

blank_issues_enabled: true
contact_links:
  - name: 🌐 Discuss an idea
    url: https://github.com/WindowsMEMZ/Greatdori/discussions
    about: >
      Share an idea with the community.
