# This source file is part of the Greatdori! open source project
#
# Copyright (c) 2025 the Greatdori! project authors
# Licensed under Apache License v2.0
#
# See https://greatdori.memz.top/LICENSE.txt for license information
# See https://greatdori.memz.top/CONTRIBUTORS.txt for the list of Greatdori! project authors

name: 🌟 Request a change
description: >
  Request a feature, improvement, or other change.
labels: [improvement, triage needed]
body:
  - type: textarea
    attributes:
      label: Motivation
      description: >
        Describe the problems that this idea seeks to address. If the
        problem is that some common pattern is currently hard to express, show
        how one can currently get a similar effect and describe its drawbacks.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: >
        Describe the solution to the problem. Provide examples and describe how
        they work. Show how this solution is better than current workarounds: is
        it cleaner, safer, or more efficient?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: >
        Any complementary information that could be valuable to an author of
        an implementor or future discussions.
    validations:
      required: false
