#===---*- Greatdori! -*----------------------------------------------------===#
#
# build-greatdori.yml
#
# This source file is part of the Greatdori! open source project
#
# Copyright (c) 2025 the Greatdori! project authors
# Licensed under Apache License v2.0
#
# See https://greatdori.memz.top/LICENSE.txt for license information
# See https://greatdori.memz.top/CONTRIBUTORS.txt for the list of Greatdori! project authors
#
#===-----------------------------------------------------------------------===#

name: Build Greatdori

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: macos-26
    strategy:
      matrix:
        destination: ["macOS", "iOS Simulator", "iOS"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Remove runner local related libs
        run: brew remove --ignore-dependencies libssh2
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_26.0.app
      - name: Create build folder
        run: mkdir build
      - name: Build
        run: xcodebuild -project Greatdori.xcodeproj -scheme Greatdori -configuration Release -derivedDataPath ./build -destination "generic/platform=${{ matrix.destination }}" build CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_STYLE=Manual DEVELOPMENT_TEAM=""
      - name: Upload build result
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Greatdori-${{ matrix.destination }}.app
          path: ./build/Build/Products/*/Greatdori!.app
          if-no-files-found: error
